# Generated by Django 3.2.8 on 2021-11-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211125_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('voiture', 'numero')},
        ),
    ]
