# Generated by Django 3.2.8 on 2021-11-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_place_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='prix',
        ),
        migrations.AlterUniqueTogether(
            name='voiture',
            unique_together={('train', 'numero')},
        ),
    ]
