# Generated by Django 3.2.8 on 2021-11-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211125_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
