# Generated by Django 3.2.8 on 2021-11-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20211125_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='prenom',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.reduction'),
        ),
    ]
