# Generated by Django 3.2.8 on 2021-11-29 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211129_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 29)),
            preserve_default=False,
        ),
    ]
