# Generated by Django 3.2.8 on 2021-12-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20211130_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
