# Generated by Django 3.2.8 on 2021-12-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_customuser_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_naissance',
            field=models.DateField(default='1990-12-12'),
            preserve_default=False,
        ),
    ]
