# Generated by Django 3.2.8 on 2021-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_reservation_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='user_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
