# Generated by Django 3.2.8 on 2021-12-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_reduction_user_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='agence',
        ),
        migrations.DeleteModel(
            name='Agence',
        ),
    ]
