# Generated by Django 3.2.8 on 2021-12-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20211203_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='places_libres',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de places libres'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.train'),
        ),
    ]
